pooling层的提出是为了缓解卷积层对位置的过度敏感性．

分类：最大池化，平均池化

稍微复杂点：考虑池化窗口的填充，步幅（与卷积过程类似）

池化与卷积不同的有，池化的过程是分通道的，池化结果的通道数与输入相一致; (卷积是分别每个通道单独卷积后相加)

In [1]:
import torch
from torch import nn

def pool2d(X, pool_size, mode='max'):
    X = X.float()
    p_h, p_w = pool_size
    Y = torch.zeros(X.shape[0] - p_h + 1, X.shape[1] - p_w + 1)
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            if mode == 'max':
                Y[i, j] = X[i:i+p_h, j:j+p_w].max()
            elif mode == 'avg':
                Y[i, j] = X[i:i+p_h, j:j+p_w].mean()
    return Y

In [2]:
X = torch.tensor([
        [0, 1, 2],
        [3, 4, 5],
        [6, 7, 8],
    ])
pool2d(X, (2, 2))

tensor([[4., 5.],
        [7., 8.]])

In [3]:

pool2d(X, (2, 2), mode='avg')

tensor([[2., 3.],
        [5., 6.]])

In [6]:
### 填充与步幅
X = torch.arange(16, dtype=torch.float).view((1, 1, 4, 4))

pool2d = nn.MaxPool2d(3)
pool2d(X)

tensor([[[[10.]]]])

In [7]:
# 指定stride和padding
pool2d = nn.MaxPool2d(3, padding=1, stride=2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

In [9]:
# 指定非正方形的stride和padding
pool2d = nn.MaxPool2d((2, 4), padding=(1, 2), stride=(2, 3))
pool2d(X)

tensor([[[[ 1.,  3.],
          [ 9., 11.],
          [13., 15.]]]])

In [10]:
### 多通道
Ｘ = torch.cat((X, X+1), dim=1)  # 1代表通道维度，２是Ｈeight, 3是Ｗidth
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]],

         [[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]])

In [12]:
pool2d = nn.MaxPool2d(3, padding=1, stride=2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]],

         [[ 6.,  8.],
          [14., 16.]]]])