## 1. 基本数据结构 Tensor

In [ ]:
import torch

In [6]:
x = torch.empty(5, 3)
print(x)

tensor([[ 3.0380e+37,  4.5674e-41, -3.3397e-34],
        [ 4.5674e-41, -3.3397e-34,  4.5674e-41],
        [-3.3397e-34,  4.5674e-41, -3.3397e-34],
        [ 4.5674e-41, -3.3398e-34,  4.5674e-41],
        [-7.6836e-38,  4.5674e-41,  0.0000e+00]])


In [7]:
x = torch.rand(5, 3)
print(x)

tensor([[0.0897, 0.6923, 0.1438],
        [0.7116, 0.9541, 0.1924],
        [0.2275, 0.3997, 0.7222],
        [0.4219, 0.3344, 0.0297],
        [0.3987, 0.5073, 0.6031]])


In [9]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [12]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [13]:
x = x.new_ones(5, 3, dtype=torch.float64)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [14]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[-0.2047, -1.2342, -2.2128],
        [ 0.9800, -1.7206, -0.8228],
        [ 0.2044, -1.0403,  0.3521],
        [ 1.0229,  0.0534, -0.3430],
        [-0.2562, -0.0306, -0.5474]])


In [15]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


In [26]:
x = torch.arange(1, 5, 1)
print(x)

tensor([1, 2, 3, 4])


In [21]:
y = torch.linspace(1,5,1)
print(y)

tensor([1.])


## 2. 数据运算
### 2.1 算数运算 (加法为例)
### 2.2 索引
### 2.3 改变形状
### 2.4 线性代数

In [27]:
y = torch.rand(5,3)
x = torch.rand(5,3)
print(x+y)

tensor([[0.2251, 1.4605, 1.4389],
        [1.1731, 0.7038, 1.4061],
        [0.9654, 0.8661, 0.9387],
        [0.9333, 0.8942, 0.6523],
        [0.8230, 0.4693, 0.4189]])


In [28]:
print(torch.add(x, y))

tensor([[0.2251, 1.4605, 1.4389],
        [1.1731, 0.7038, 1.4061],
        [0.9654, 0.8661, 0.9387],
        [0.9333, 0.8942, 0.6523],
        [0.8230, 0.4693, 0.4189]])


In [30]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.2251, 1.4605, 1.4389],
        [1.1731, 0.7038, 1.4061],
        [0.9654, 0.8661, 0.9387],
        [0.9333, 0.8942, 0.6523],
        [0.8230, 0.4693, 0.4189]])


In [32]:
y.add_(x)
print(y)

tensor([[0.3780, 2.3314, 2.1188],
        [1.6050, 1.0253, 1.8703],
        [1.8945, 1.4450, 1.6032],
        [1.8244, 1.6671, 0.8939],
        [1.6029, 0.4936, 0.6524]])


### 索引

In [34]:
y = x[0, :]
y += 1
print(y)
print(x[0, :])   # 索引时会更改源tensor

tensor([2.1529, 2.8710, 2.6799])
tensor([2.1529, 2.8710, 2.6799])


### 改变形状

In [37]:
# view仅仅是改变了对这个张量的观察角度，内部数据并未改变。
# 虽然view返回的Tensor与源Tensor是共享data的，
# 但是依然是一个新的Tensor（因为Tensor除了包含data外还有一些其他属性），
# 二者id（内存地址）并不一致。

y = x.view(15)
z = x.view(-1, 5)   
print(x.size(), y.size(), z.size())
print(x, y, z)

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])
tensor([[2.1529, 2.8710, 2.6799],
        [0.4319, 0.3214, 0.4642],
        [0.9291, 0.5789, 0.6645],
        [0.8911, 0.7729, 0.2416],
        [0.7800, 0.0242, 0.2334]]) tensor([2.1529, 2.8710, 2.6799, 0.4319, 0.3214, 0.4642, 0.9291, 0.5789, 0.6645,
        0.8911, 0.7729, 0.2416, 0.7800, 0.0242, 0.2334]) tensor([[2.1529, 2.8710, 2.6799, 0.4319, 0.3214],
        [0.4642, 0.9291, 0.5789, 0.6645, 0.8911],
        [0.7729, 0.2416, 0.7800, 0.0242, 0.2334]])


In [40]:
# 返回一个真正新的副本（即不共享data内存）该怎么办？ 先clone, 后view

x_cp = x.clone().view(15)
x -= 1
print(x)
print(x_cp)

tensor([[ 1.1529,  1.8710,  1.6799],
        [-0.5681, -0.6786, -0.5358],
        [-0.0709, -0.4211, -0.3355],
        [-0.1089, -0.2271, -0.7584],
        [-0.2200, -0.9758, -0.7666]])
tensor([2.1529, 2.8710, 2.6799, 0.4319, 0.3214, 0.4642, 0.9291, 0.5789, 0.6645,
        0.8911, 0.7729, 0.2416, 0.7800, 0.0242, 0.2334])


In [56]:
# item 改变形状 可以将一个标量Tensor转换成一个Python number

x = torch.randn(1)
print(x)
print(x.item())  # 其实是将里面的数据取出来

tensor([-0.5315])
-0.5315312743186951


In [ ]:
# reshape() 不被推荐使用，因为它的返回值很难被确定是原tensor的拷贝。

### 线性代数

## 3. 广播机制

In [46]:
x = torch.arange(1, 3).view(1, 2)
print(x)
y = torch.arange(1, 4).view(3, 1)
print(y)
print(x+y)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


## 4. 运算的内存开销

In [50]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)   # 查看内存地址
print(id_before)
y = y + x           # 此时已经开辟了新内存
print(id(y) == id_before)   # 查看是否开辟新内存

139991783163008
False


In [52]:
# 通过索引的方式进行替换操作，即将结果写进原内存中, 减少内存开销
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y[:] = y + x
print(id(y) == id_before)

True


In [53]:
# 使用运算符全名函数中的out参数
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
torch.add(x, y, out=y)
print(id(y) == id_before)

True


In [54]:
# 使用自加运算符+=(也即add_())
x = torch.tensor([1, 2])
y = torch.tensor([3, 5])
id_before = id(y)
y.add_(x)
print(id(y) == id_before)

True


## 5. Tensor 与 Numpy 相互转换

In [2]:
import torch

#### Tensor 转 Numpy数组

In [5]:
a = torch.ones(5)
b = a.numpy()    # 他们之间会共享同一块内存，对任意一方进行改变都会改变另一方
print(a, b)

a += 1
print(a, b)

b += 1
print(a, b)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


#### Numpy数组 转  Tensor 

In [8]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)# 他们之间会共享同一块内存，对任意一方进行改变都会改变另一方
print(a, b)

a += 1
print(a, b)

b += 1
print(a, b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [9]:
c = torch.tensor(a)   # 该方法torch.tensor(a) 与 上面的from_numpy(a)不同
a += 1
print(a, c)

[4. 4. 4. 4. 4.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


## 6. Tensor on GPU

In [12]:
### to方法

x = torch.randn([3, 3])

if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x+y
    print(z)
    print(z.to("cpu", torch.double))

tensor([[0.5586, 1.8965, 1.4620],
        [1.0808, 1.0426, 0.5818],
        [1.0459, 1.6393, 1.7602]], device='cuda:0')
tensor([[0.5586, 1.8965, 1.4620],
        [1.0808, 1.0426, 0.5818],
        [1.0459, 1.6393, 1.7602]], dtype=torch.float64)
